"""bbl changed to bigint pluto

Revision ID: 3688bb518a77
Revises: 91db6e9e3ab1
Create Date: 2024-03-10 16:45:17.244201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3688bb518a77'
down_revision = '91db6e9e3ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pluto_info', schema=None) as batch_op:
        batch_op.alter_column('bbl',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pluto_info', schema=None) as batch_op:
        batch_op.alter_column('bbl',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
