"""associated building-units

Revision ID: 767c8b11a95e
Revises: c452bd7df59d
Create Date: 2024-01-02 22:40:29.025512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767c8b11a95e'
down_revision = 'c452bd7df59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'buildings', ['building_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('building_id')

    # ### end Alembic commands ###
