"""ucbbl changed to BigInt

Revision ID: a3cbc3c7c9aa
Revises: c766a65ad6c0
Create Date: 2024-03-08 13:45:18.576396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cbc3c7c9aa'
down_revision = 'c766a65ad6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_stab', schema=None) as batch_op:
        batch_op.alter_column('ucbbl',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_stab', schema=None) as batch_op:
        batch_op.alter_column('ucbbl',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
