"""added columns for building model

Revision ID: a95516dedf8e
Revises: 767c8b11a95e
Create Date: 2024-01-03 23:17:17.398644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95516dedf8e'
down_revision = '767c8b11a95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bldgno1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('street1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stsufx1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bldgno2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('street2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stsufx2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('county', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('block', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('lot')
        batch_op.drop_column('block')
        batch_op.drop_column('status3')
        batch_op.drop_column('status2')
        batch_op.drop_column('status1')
        batch_op.drop_column('county')
        batch_op.drop_column('city')
        batch_op.drop_column('stsufx2')
        batch_op.drop_column('street2')
        batch_op.drop_column('bldgno2')
        batch_op.drop_column('stsufx1')
        batch_op.drop_column('street1')
        batch_op.drop_column('bldgno1')
        batch_op.drop_column('zip')

    # ### end Alembic commands ###
