"""initialize rent_stab model

Revision ID: c766a65ad6c0
Revises: a95516dedf8e
Create Date: 2024-03-05 11:01:08.074033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c766a65ad6c0'
down_revision = 'a95516dedf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_stab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ucbbl', sa.Integer(), nullable=True),
    sa.Column('uc2018', sa.Integer(), nullable=True),
    sa.Column('pdfsoa2018', sa.String(length=255), nullable=True),
    sa.Column('uc2019', sa.Integer(), nullable=True),
    sa.Column('pdfsoa2019', sa.String(length=255), nullable=True),
    sa.Column('uc2020', sa.Integer(), nullable=True),
    sa.Column('pdfsoa2020', sa.String(length=255), nullable=True),
    sa.Column('uc2021', sa.Integer(), nullable=True),
    sa.Column('pdfsoa2021', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent_stab')
    # ### end Alembic commands ###
