"""added unique constraint on bbl

Revision ID: f10e00221d44
Revises: 3688bb518a77
Create Date: 2024-03-11 12:39:33.488516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10e00221d44'
down_revision = '3688bb518a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pluto_info', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['bbl'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pluto_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
